#!/bin/bash
# This hook is run after this virtualenv is activated.

# Modify and copy this file to /path/to/virtualenv/bin/postactivate
export PYTHONPATH="/Users/jboyd/Dropbox/think_stats/official_code":$PYTHONPATH
